"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.destinations = void 0;
exports.destinations = [
    // --- Original 15 Destinations ---
    {
        name: "Bali",
        country: "Indonesia",
        city: "Denpasar",
        description: "Tropical island famous for beaches, temples, and nightlife.",
        latitude: -8.3405,
        longitude: 115.092,
        averageCost: 450,
        bestSeason: "April to October",
        rating: 4.8,
        image: "https://picsum.photos/seed/Bali/800/600",
    },
    {
        name: "Paris",
        country: "France",
        city: "Paris",
        description: "City of lights known for art, romance, and historic landmarks.",
        latitude: 48.8566,
        longitude: 2.3522,
        averageCost: 800,
        bestSeason: "April to June",
        rating: 4.7,
        image: "https://picsum.photos/seed/Paris/800/600",
    },
    {
        name: "Dubai",
        country: "UAE",
        city: "Dubai",
        description: "Luxury city famous for skyscrapers, shopping malls, and desert safaris.",
        latitude: 25.2048,
        longitude: 55.2708,
        averageCost: 900,
        bestSeason: "November to March",
        rating: 4.6,
        image: "https://picsum.photos/seed/Dubai/800/600",
    },
    {
        name: "Tokyo",
        country: "Japan",
        city: "Tokyo",
        description: "Modern metropolis blending futuristic technology with tradition.",
        latitude: 35.6762,
        longitude: 139.6503,
        averageCost: 850,
        bestSeason: "March to May",
        rating: 4.9,
        image: "https://picsum.photos/seed/Tokyo/800/600",
    },
    {
        name: "Maldives",
        country: "Maldives",
        city: "Male",
        description: "Luxury island destination known for crystal-clear waters and resorts.",
        latitude: 3.2028,
        longitude: 73.2207,
        averageCost: 1200,
        bestSeason: "November to April",
        rating: 4.9,
        image: "https://picsum.photos/seed/Maldives/800/600",
    },
    {
        name: "Rome",
        country: "Italy",
        city: "Rome",
        description: "Historic city with ancient ruins, art, and famous cuisine.",
        latitude: 41.9028,
        longitude: 12.4964,
        averageCost: 700,
        bestSeason: "April to June",
        rating: 4.7,
        image: "https://picsum.photos/seed/Rome/800/600",
    },
    {
        name: "Bangkok",
        country: "Thailand",
        city: "Bangkok",
        description: "Vibrant city famous for street food, temples, and nightlife.",
        latitude: 13.7563,
        longitude: 100.5018,
        averageCost: 350,
        bestSeason: "November to February",
        rating: 4.6,
        image: "https://picsum.photos/seed/Bangkok/800/600",
    },
    {
        name: "Istanbul",
        country: "Turkey",
        city: "Istanbul",
        description: "Historic city bridging Europe and Asia with rich culture.",
        latitude: 41.0082,
        longitude: 28.9784,
        averageCost: 500,
        bestSeason: "April to May",
        rating: 4.6,
        image: "https://picsum.photos/seed/Istanbul/800/600",
    },
    {
        name: "Cape Town",
        country: "South Africa",
        city: "Cape Town",
        description: "Coastal city known for Table Mountain and beautiful beaches.",
        latitude: -33.9249,
        longitude: 18.4241,
        averageCost: 600,
        bestSeason: "November to March",
        rating: 4.7,
        image: "https://picsum.photos/seed/CapeTown/800/600",
    },
    {
        name: "New York",
        country: "USA",
        city: "New York",
        description: "Iconic city known for skyscrapers, Broadway, and diverse culture.",
        latitude: 40.7128,
        longitude: -74.006,
        averageCost: 950,
        bestSeason: "April to June",
        rating: 4.7,
        image: "https://picsum.photos/seed/NewYork/800/600",
    },
    {
        name: "Barcelona",
        country: "Spain",
        city: "Barcelona",
        description: "Mediterranean city famous for architecture and beaches.",
        latitude: 41.3851,
        longitude: 2.1734,
        averageCost: 650,
        bestSeason: "May to June",
        rating: 4.7,
        image: "https://picsum.photos/seed/Barcelona/800/600",
    },
    {
        name: "Sydney",
        country: "Australia",
        city: "Sydney",
        description: "Coastal city known for Opera House and Harbour Bridge.",
        latitude: -33.8688,
        longitude: 151.2093,
        averageCost: 900,
        bestSeason: "September to November",
        rating: 4.8,
        image: "https://picsum.photos/seed/Sydney/800/600",
    },
    {
        name: "Rio de Janeiro",
        country: "Brazil",
        city: "Rio de Janeiro",
        description: "Vibrant city known for beaches, Carnival festival, and Christ the Redeemer.",
        latitude: -22.9068,
        longitude: -43.1729,
        averageCost: 550,
        bestSeason: "December to March",
        rating: 4.6,
        image: "https://picsum.photos/seed/Rio/800/600",
    },
    {
        name: "Santorini",
        country: "Greece",
        city: "Santorini",
        description: "Famous island with white houses and stunning sunsets.",
        latitude: 36.3932,
        longitude: 25.4615,
        averageCost: 850,
        bestSeason: "May to October",
        rating: 4.9,
        image: "https://picsum.photos/seed/Santorini/800/600",
    },
    {
        name: "Singapore",
        country: "Singapore",
        city: "Singapore",
        description: "Modern city-state known for cleanliness, gardens, and food culture.",
        latitude: 1.3521,
        longitude: 103.8198,
        averageCost: 700,
        bestSeason: "February to April",
        rating: 4.8,
        image: "https://picsum.photos/seed/Singapore/800/600",
    },
    // --- 25 New Destinations ---
    {
        name: "London",
        country: "UK",
        city: "London",
        description: "Historic capital offering royal landmarks, museums, and diverse neighborhoods.",
        latitude: 51.5074,
        longitude: -0.1278,
        averageCost: 850,
        bestSeason: "May to September",
        rating: 4.7,
        image: "https://picsum.photos/seed/London/800/600",
    },
    {
        name: "Amsterdam",
        country: "Netherlands",
        city: "Amsterdam",
        description: "Charming city famous for its canals, cycling culture, and art museums.",
        latitude: 52.3676,
        longitude: 4.9041,
        averageCost: 750,
        bestSeason: "April to October",
        rating: 4.8,
        image: "https://picsum.photos/seed/Amsterdam/800/600",
    },
    {
        name: "Kyoto",
        country: "Japan",
        city: "Kyoto",
        description: "Ancient city known for traditional wooden houses, classical Buddhist temples, and gardens.",
        latitude: 35.0116,
        longitude: 135.7681,
        averageCost: 800,
        bestSeason: "March to May",
        rating: 4.9,
        image: "https://picsum.photos/seed/Kyoto/800/600",
    },
    {
        name: "Machu Picchu",
        country: "Peru",
        city: "Cusco",
        description: "Iconic Incan citadel set high in the Andes Mountains.",
        latitude: -13.1631,
        longitude: -72.545,
        averageCost: 450,
        bestSeason: "May to October",
        rating: 4.9,
        image: "https://picsum.photos/seed/MachuPicchu/800/600",
    },
    {
        name: "Prague",
        country: "Czech Republic",
        city: "Prague",
        description: "Nicknamed 'the City of a Hundred Spires,' known for Old Town Square and historic charm.",
        latitude: 50.0755,
        longitude: 14.4378,
        averageCost: 500,
        bestSeason: "May to September",
        rating: 4.7,
        image: "https://picsum.photos/seed/Prague/800/600",
    },
    {
        name: "Reykjavik",
        country: "Iceland",
        city: "Reykjavik",
        description: "Gateway to striking volcanic landscapes, hot springs, and the Northern Lights.",
        latitude: 64.1466,
        longitude: -21.9426,
        averageCost: 1000,
        bestSeason: "June to August",
        rating: 4.8,
        image: "https://picsum.photos/seed/Reykjavik/800/600",
    },
    {
        name: "Banff",
        country: "Canada",
        city: "Banff",
        description: "Resort town located within Banff National Park, famous for its mountainous surroundings.",
        latitude: 51.1784,
        longitude: -115.5708,
        averageCost: 800,
        bestSeason: "June to August",
        rating: 4.9,
        image: "https://picsum.photos/seed/Banff/800/600",
    },
    {
        name: "Seoul",
        country: "South Korea",
        city: "Seoul",
        description: "A huge metropolis where modern skyscrapers, high-tech subways, and pop culture meet Buddhist temples.",
        latitude: 37.5665,
        longitude: 126.978,
        averageCost: 750,
        bestSeason: "September to November",
        rating: 4.7,
        image: "https://picsum.photos/seed/Seoul/800/600",
    },
    {
        name: "Queenstown",
        country: "New Zealand",
        city: "Queenstown",
        description: "The adventure capital of the world, sitting on the shores of the South Island's Lake Wakatipu.",
        latitude: -45.0312,
        longitude: 168.6626,
        averageCost: 850,
        bestSeason: "December to February",
        rating: 4.9,
        image: "https://picsum.photos/seed/Queenstown/800/600",
    },
    {
        name: "Marrakech",
        country: "Morocco",
        city: "Marrakech",
        description: "A major economic center and home to mosques, palaces, and vibrant markets.",
        latitude: 31.6295,
        longitude: -7.9811,
        averageCost: 450,
        bestSeason: "March to May",
        rating: 4.6,
        image: "https://picsum.photos/seed/Marrakech/800/600",
    },
    {
        name: "Honolulu",
        country: "USA",
        city: "Honolulu",
        description: "Capital of Hawaii, known for the iconic crescent beach of Waikiki.",
        latitude: 21.3069,
        longitude: -157.8583,
        averageCost: 950,
        bestSeason: "April to June",
        rating: 4.8,
        image: "https://picsum.photos/seed/Honolulu/800/600",
    },
    {
        name: "Venice",
        country: "Italy",
        city: "Venice",
        description: "Built on more than 100 small islands in a lagoon, famous for no roads, just canals.",
        latitude: 45.4408,
        longitude: 12.3155,
        averageCost: 800,
        bestSeason: "September to November",
        rating: 4.6,
        image: "https://picsum.photos/seed/Venice/800/600",
    },
    {
        name: "Hong Kong",
        country: "China",
        city: "Hong Kong",
        description: "A bustling urban center known for its skyline, deep natural harbor, and rich food scene.",
        latitude: 22.3193,
        longitude: 114.1694,
        averageCost: 850,
        bestSeason: "October to December",
        rating: 4.6,
        image: "https://picsum.photos/seed/HongKong/800/600",
    },
    {
        name: "Bora Bora",
        country: "French Polynesia",
        city: "Vaitape",
        description: "Small South Pacific island known for its luxury aqua-centric resorts and scuba diving.",
        latitude: -16.5004,
        longitude: -151.7415,
        averageCost: 1500,
        bestSeason: "May to October",
        rating: 4.9,
        image: "https://picsum.photos/seed/BoraBora/800/600",
    },
    {
        name: "Buenos Aires",
        country: "Argentina",
        city: "Buenos Aires",
        description: "Cosmopolitan capital characterized by its eclectic architecture and tango dancing.",
        latitude: -34.6037,
        longitude: -58.3816,
        averageCost: 500,
        bestSeason: "September to November",
        rating: 4.6,
        image: "https://picsum.photos/seed/BuenosAires/800/600",
    },
    {
        name: "Cairo",
        country: "Egypt",
        city: "Cairo",
        description: "Sprawling capital, set on the Nile River, famous for the nearby Giza pyramid complex.",
        latitude: 30.0444,
        longitude: 31.2357,
        averageCost: 400,
        bestSeason: "October to April",
        rating: 4.5,
        image: "https://picsum.photos/seed/Cairo/800/600",
    },
    {
        name: "Phuket",
        country: "Thailand",
        city: "Phuket",
        description: "A rainforested, mountainous island known for some of Thailand’s most popular beaches.",
        latitude: 7.8804,
        longitude: 98.3923,
        averageCost: 400,
        bestSeason: "November to April",
        rating: 4.6,
        image: "https://picsum.photos/seed/Phuket/800/600",
    },
    {
        name: "Vancouver",
        country: "Canada",
        city: "Vancouver",
        description: "A bustling west coast seaport surrounded by mountains and a thriving art scene.",
        latitude: 49.2827,
        longitude: -123.1207,
        averageCost: 750,
        bestSeason: "June to September",
        rating: 4.7,
        image: "https://picsum.photos/seed/Vancouver/800/600",
    },
    {
        name: "Vienna",
        country: "Austria",
        city: "Vienna",
        description: "Known for its Imperial palaces, historic architecture, and classical music legacy.",
        latitude: 48.2082,
        longitude: 16.3738,
        averageCost: 700,
        bestSeason: "April to October",
        rating: 4.8,
        image: "https://picsum.photos/seed/Vienna/800/600",
    },
    {
        name: "San Francisco",
        country: "USA",
        city: "San Francisco",
        description: "Famous for the Golden Gate Bridge, steep streets, and diverse neighborhoods.",
        latitude: 37.7749,
        longitude: -122.4194,
        averageCost: 900,
        bestSeason: "September to November",
        rating: 4.7,
        image: "https://picsum.photos/seed/SanFrancisco/800/600",
    },
    {
        name: "Taipei",
        country: "Taiwan",
        city: "Taipei",
        description: "A modern metropolis with Japanese colonial lanes, busy shopping streets, and contemporary buildings.",
        latitude: 25.033,
        longitude: 121.5654,
        averageCost: 600,
        bestSeason: "September to November",
        rating: 4.7,
        image: "https://picsum.photos/seed/Taipei/800/600",
    },
    {
        name: "Las Vegas",
        country: "USA",
        city: "Las Vegas",
        description: "Internationally renowned major resort city known for gambling, shopping, and entertainment.",
        latitude: 36.1699,
        longitude: -115.1398,
        averageCost: 700,
        bestSeason: "March to May",
        rating: 4.5,
        image: "https://picsum.photos/seed/LasVegas/800/600",
    },
    {
        name: "Hanoi",
        country: "Vietnam",
        city: "Hanoi",
        description: "Known for its centuries-old architecture and a rich culture with Southeast Asian, Chinese and French influences.",
        latitude: 21.0285,
        longitude: 105.8542,
        averageCost: 300,
        bestSeason: "February to April",
        rating: 4.7,
        image: "https://picsum.photos/seed/Hanoi/800/600",
    },
    {
        name: "Miami",
        country: "USA",
        city: "Miami",
        description: "A vibrant city known for its beautiful beaches, art deco architecture, and Latin-American cultural influences.",
        latitude: 25.7617,
        longitude: -80.1918,
        averageCost: 850,
        bestSeason: "November to April",
        rating: 4.6,
        image: "https://picsum.photos/seed/Miami/800/600",
    },
    {
        name: "Shanghai",
        country: "China",
        city: "Shanghai",
        description: "A global financial hub offering a stunning skyline and the historic Bund waterfront.",
        latitude: 31.2304,
        longitude: 121.4737,
        averageCost: 700,
        bestSeason: "September to November",
        rating: 4.6,
        image: "https://picsum.photos/seed/Shanghai/800/600",
    },
];
