export const guides = [
  {
    name: "Liam Carter",
    email: "guide1@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000002",
    country: "USA",
    bio: "Adventure tour guide with 8 years experience.",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Noah Walker",
    email: "guide2@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000003",
    country: "Canada",
    bio: "Mountain trekking specialist.",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    name: "Oliver Scott",
    email: "guide3@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000004",
    country: "UK",
    bio: "Cultural and heritage tour guide.",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Elijah Adams",
    email: "guide4@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000005",
    country: "Australia",
    bio: "Nature and wildlife expert.",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    name: "James Turner",
    email: "guide5@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000006",
    country: "Italy",
    bio: "European city tour expert.",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    name: "Benjamin Hill",
    email: "guide6@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000007",
    country: "Spain",
    bio: "Food and culture travel guide.",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    name: "Lucas Green",
    email: "guide7@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000008",
    country: "Brazil",
    bio: "Beach and festival tour organizer.",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    name: "Henry Baker",
    email: "guide8@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000009",
    country: "France",
    bio: "Historic landmark guide.",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    name: "Alexander Perez",
    email: "guide9@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000010",
    country: "Mexico",
    bio: "City walking tour specialist.",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    name: "Michael Cooper",
    email: "guide10@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000011",
    country: "Japan",
    bio: "Cultural and temple tour expert.",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    name: "Daniel Reed",
    email: "guide11@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000012",
    country: "Thailand",
    bio: "Nightlife and beach tours.",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    name: "Matthew Cox",
    email: "guide12@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000013",
    country: "Indonesia",
    bio: "Island adventure guide.",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    name: "Jackson Flores",
    email: "guide13@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000014",
    country: "South Africa",
    bio: "Safari and wildlife guide.",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    name: "Sebastian Morris",
    email: "guide14@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000015",
    country: "Turkey",
    bio: "Historic tour expert.",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    name: "David Rogers",
    email: "guide15@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000016",
    country: "UAE",
    bio: "Desert safari specialist.",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    name: "Joseph Bell",
    email: "guide16@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000017",
    country: "Greece",
    bio: "Island exploration guide.",
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    name: "Samuel Murphy",
    email: "guide17@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000018",
    country: "Portugal",
    bio: "City tour and local culture expert.",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    name: "Andrew Bailey",
    email: "guide18@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000019",
    country: "Germany",
    bio: "Museum and history guide.",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    name: "Joshua Rivera",
    email: "guide19@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000020",
    country: "Netherlands",
    bio: "Urban exploration specialist.",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    name: "Christopher Cook",
    email: "guide20@tourbuddy.com",
    password: "userrole123@#",
    role: "GUIDE",
    phone: "+10000000021",
    country: "Singapore",
    bio: "City and food tour guide.",
    avatar: "https://randomuser.me/api/portraits/men/20.jpg",
  },
];
